DROP SEQUENCE SQ_RHSTU_ESTADO;

DROP SEQUENCE SQ_RHSTU_CIDADE;

DROP SEQUENCE SQ_RHSTU_BAIRRO

DROP SEQUENCE SQ_RHSTU_LOGRADOURO;

DROP SEQUENCE SQ_RHSTU_TUPO_CONTATO;

DROP SEQUENCE SQ_RHSTU_ENDERECO_PACIENTE;

DROP SEQUENCE SQ_RHSTU_UNID_HOSPITALAR;

DROP SEQUENCE SQ_RHSTU_MEDICO;

DROP SEQUENCE SQ_RHSTU_MEDICAMENTO;

DROP SEQUENCE SQ_RHSTU_PRESCRICAO_MEDICA;

DROP SEQUENCE SQ_RHSTU_PACIENTE;

DROP SEQUENCE SQ_RHSTU_EMAIL_PACIENTE;

DROP SEQUENCE SQ_RHSTU_PLANO_SAUDE;

DROP SEQUENCE SQ_RHSTU_PACIENTE_PLANO_SAUDE;

DROP SEQUENCE SQ_RHSTU_FORMA_PAGAMENTO;

DROP SEQUENCE SQ_RHSTU_CONSULTA_FORMA_PAGTO;